# Run tests on a random port
server.port=0

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.username=system
spring.datasource.password=Dharma@2628
spring.datasource.driver-class-name=org.h2.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable security for tests (optional)
spring.security.user.name=system
spring.security.user.password=Dharma@2628